// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:salon_app_commons/salon_app_commons.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    logger.d('flavor:$flavor');
    logger.d('kIsWeb:$kIsWeb');

    if (flavor == 'dev') {
      if (kIsWeb) {
        return devWeb;
      }
      switch (defaultTargetPlatform) {
        case TargetPlatform.android:
          return devAndroid;
        case TargetPlatform.iOS:
          return devIos;
        default:
          throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.',
          );
      }
    } else {
      if (kIsWeb) {
        return prodWeb;
      }
      switch (defaultTargetPlatform) {
        case TargetPlatform.android:
          return prodAndroid;
        case TargetPlatform.iOS:
          return prodIos;
        default:
          throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.',
          );
      }
    }
  }

  static const FirebaseOptions devWeb = FirebaseOptions(
    apiKey: 'AIzaSyADEIryE6x3-3MXLacjW4I8XVkVM9pJxMs',
    appId: '1:386988152963:web:e44e94a4f7f0dbb712e3b6',
    messagingSenderId: '386988152963',
    projectId: 'kboy-salon-app',
    authDomain: 'kboy-salon-app.firebaseapp.com',
    databaseURL: 'https://kboy-salon-app.firebaseio.com',
    storageBucket: 'kboy-salon-app.appspot.com',
    measurementId: 'G-M7X773TQ4V',
  );

  static const FirebaseOptions prodWeb = FirebaseOptions(
    apiKey: 'AIzaSyBCqUvo1_ZIN-Kjeo_0W6vnBGNqPKWGw0c',
    appId: '1:93473949394:web:0f66ad7df58344df4ecf0b',
    messagingSenderId: '93473949394',
    projectId: 'kboy-salon-app-prod',
    authDomain: 'kboy-salon-app-prod.firebaseapp.com',
    databaseURL: 'https://kboy-salon-app-prod.firebaseio.com',
    storageBucket: 'kboy-salon-app-prod.appspot.com',
    measurementId: 'G-G66E6JDRH5',
  );

  static const FirebaseOptions devAndroid = FirebaseOptions(
    apiKey: 'AIzaSyBRARp-tgh2C-mGs_vokdHHjlsynLrVg8Q',
    appId: '1:386988152963:android:9d5c78809f28408812e3b6',
    messagingSenderId: '386988152963',
    projectId: 'kboy-salon-app',
    databaseURL: 'https://kboy-salon-app.firebaseio.com',
    storageBucket: 'kboy-salon-app.appspot.com',
  );

  static const FirebaseOptions devIos = FirebaseOptions(
    apiKey: 'AIzaSyCS00Tcx8VjVtX_bmJIJAC6f_jBWWHg5Lw',
    appId: '1:386988152963:ios:04612684221ec38f12e3b6',
    messagingSenderId: '386988152963',
    projectId: 'kboy-salon-app',
    databaseURL: 'https://kboy-salon-app.firebaseio.com',
    storageBucket: 'kboy-salon-app.appspot.com',
    iosClientId:
        '386988152963-ror2m8ioeh3f51pf25a2aj16d9rjq2s4.apps.googleusercontent.com',
    iosBundleId: 'jp.kboy.kboyflutteruniv.dev',
  );

  static const FirebaseOptions prodAndroid = FirebaseOptions(
    apiKey: 'AIzaSyBQE4ziQBZ2dQ4Bw7p5MG82cm6yWgnYzVQ',
    appId: '1:93473949394:android:7107ee565110dfdb4ecf0b',
    messagingSenderId: '93473949394',
    projectId: 'kboy-salon-app-prod',
    databaseURL: 'https://kboy-salon-app-prod.firebaseio.com',
    storageBucket: 'kboy-salon-app-prod.appspot.com',
  );

  static const FirebaseOptions prodIos = FirebaseOptions(
    apiKey: 'AIzaSyAQAiKzDAws8FIInL-XQ9mulJLLMizKn3c',
    appId: '1:93473949394:ios:2b39eaacade421554ecf0b',
    messagingSenderId: '93473949394',
    projectId: 'kboy-salon-app-prod',
    databaseURL: 'https://kboy-salon-app-prod.firebaseio.com',
    storageBucket: 'kboy-salon-app-prod.appspot.com',
    iosClientId:
        'com.googleusercontent.apps.93473949394-f6h1odcn1v6m0838luimhj6cjvga3q6e',
    iosBundleId: 'jp.kboy.kboyflutteruniv',
  );
}
